registries:
  npm-github:
    token: ${{ secrets.MY_GITHUB_PERSONAL_TOKEN }}
    type: npm-registry
    url: https://npm.pkg.github.com
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - directory: /
    groups:
      eslint:
        patterns:
          - '@eslint/*'
          - '@html-eslint/*'
          - '@stylistic/*'
          - eslint
          - eslint-*
          - typescript-eslint
      minor-and-patch:
        exclude-patterns:
          - '@eslint/*'
          - '@html-eslint/*'
          - '@stylistic/*'
          - '@vitest/*'
          - eslint
          - eslint-*
          - typescript-eslint
          - vitest
        update-types:
          - minor
          - patch
      vitest:
        patterns:
          - '@vitest/*'
          - vitest
    package-ecosystem: npm
    registries:
      - npm-github
    schedule:
      interval: weekly
version: 2
