sonar.projectKey=OlivierZal_com.melcloud
sonar.organization=olivierzal
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=**/*.jpg,**/*.png,coverage/**,settings/index.mjs,widgets/*/public/index.mjs
sonar.coverage.exclusions=tests/**,**/*.config.*,**/public/**,settings/**,scripts/**
sonar.cpd.exclusions=**/*.config.*,settings/index.html,widgets/*/public/index.html
