sonar.projectKey=OlivierZal_com.melcloud
sonar.organization=olivierzal
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=eslint-utils/**,tests/**,**/*.config.*,**/public/**,settings/**
sonar.cpd.exclusions=settings/dom.mts,settings/zones.mts,widgets/*/public/dom.mts,widgets/*/public/zones.mts,widgets/*/public/homey-api.mts