sonar.projectKey=OlivierZal_com.melcloud
sonar.organization=olivierzal
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=**/*.jpg,**/*.png,coverage/**
sonar.coverage.exclusions=tests/**,**/*.config.*,scripts/bundle.mts,scripts/sync-capability-definitions.mts,widgets/charts/public/index.mts
sonar.cpd.exclusions=**/*.config.*,settings/index.html,widgets/*/public/index.html
