jobs:
  audit:
    name: Audit
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          cache: npm
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: '@olivierzal'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm audit --audit-level=high --omit=dev
    timeout-minutes: 15
name: Audit
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch: {}
permissions: {}
