concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}
jobs:
  check:
    name: Check
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          cache: npm
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: '@olivierzal'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci --ignore-scripts
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run format
    timeout-minutes: 15
  test:
    name: Test (Node ${{ matrix.node-version }})
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: '@olivierzal'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci --ignore-scripts
      - run: npm test -- --coverage
      - if: matrix.node-version == 22 && (github.event_name == 'push' || (github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository))
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, latest, 'lts/*']
    timeout-minutes: 20
name: CI
on:
  pull_request: {}
  push:
    branches: [main]
permissions: {}
