# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: OlivierZal/configs/.github/workflows/dependabot.yml@8e7ae72e9efcbb5b201ea9e43e248ea5f9d2da76 # v4.1.0
name: dependabot
on:
  pull_request: {}
permissions: {}
