# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: OlivierZal/configs/.github/workflows/dependabot.yml@dd5ebe19d5b7f3381c34aa25ccba6ce7f324116f # v4.0.0
name: dependabot
on:
  pull_request: {}
permissions: {}
