# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependency-review:
    permissions:
      contents: read
    uses: OlivierZal/configs/.github/workflows/dependency-review.yml@69361d84fae1d0d460da2308d41c140c0762a38b # v6.5.0
name: Dependency review
on:
  pull_request: {}
permissions: {}
