# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependency-review:
    permissions:
      contents: read
    uses: OlivierZal/configs/.github/workflows/dependency-review.yml@d16eeb9fc509675429d325016c86038e555dc69e # v7.0.0
name: Dependency review
on:
  pull_request: {}
permissions: {}
