# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  dependency-review:
    permissions:
      contents: read
    uses: OlivierZal/configs/.github/workflows/dependency-review.yml@9b69e8520dfd11484df292ca75c10d51beba75ca # v6.3.1
name: Dependency review
on:
  pull_request: {}
permissions: {}
