# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  pr_title:
    permissions:
      pull-requests: read
    uses: OlivierZal/configs/.github/workflows/pr-title.yml@6932d7af8f2c21600bd7dc945062fe1a66d7db26 # v1.3.0
name: pr-title
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
permissions: {}
