# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  pr_title:
    permissions:
      pull-requests: read
    uses: OlivierZal/configs/.github/workflows/pr-title.yml@802b7e1bd61d37420efa982eb471356711b46251 # v3.2.0
name: pr-title
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
permissions: {}
