# Calls the family workflow of the same name in OlivierZal/configs.
jobs:
  pr_title:
    permissions:
      pull-requests: read
    uses: OlivierZal/configs/.github/workflows/pr-title.yml@f691686d44753b0dfb00a155c42ea66d89d78a1e # v6.1.0
name: pr-title
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
permissions: {}
