jobs:
  publish:
    permissions:
      contents: read
      packages: read
    secrets:
      HOMEY_PAT: ${{ secrets.HOMEY_PAT }}
    uses: OlivierZal/homey-kit/.github/workflows/reusable-homey-publish.yml@a6870e7e28cb90bdbfaedd3674039468ebf42f05 # v6.2.0
    with:
      bundles: |
        settings/index.js
        settings/index.mjs
        widgets/ata-group-setting/public/index.js
        widgets/ata-group-setting/public/index.mjs
        widgets/charts/public/index.js
        widgets/charts/public/index.mjs
name: Publish app on Homey
on:
  release:
    types: [published]
  workflow_dispatch: {}
permissions: {}
