jobs:
  publish:
    name: Publish app on Homey
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: latest
          registry-url: https://npm.pkg.github.com
          scope: '@olivierzal'
      - run: cp $NPM_CONFIG_USERCONFIG ${{ github.workspace }}/.npmrc
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: publish
        name: Publish
        uses: athombv/github-action-homey-app-publish@master
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}
      - name: URL
        run: echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
name: Publish app on Homey
on: workflow_dispatch
