concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: validate-${{ github.ref }}
jobs:
  validate:
    permissions:
      contents: read
      packages: read
    uses: OlivierZal/homey-kit/.github/workflows/reusable-homey-validate.yml@31906424d9b11651c26c5bd4ae4a393f48e9590e # v6.2.1
name: Validate
on:
  pull_request: {}
  push:
    branches: [main]
permissions: {}
