concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: validate-${{ github.ref }}
jobs:
  validate:
    permissions:
      contents: read
      packages: read
    uses: OlivierZal/homey-kit/.github/workflows/reusable-homey-validate.yml@eeddc9c50810f7a54dc3862fa328d621e6200406 # v7.0.0
name: Validate
on:
  pull_request: {}
  push:
    branches: [main]
permissions: {}
