concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: validate-${{ github.ref }}
jobs:
  validate:
    permissions:
      contents: read
      packages: read
    uses: OlivierZal/homey-kit/.github/workflows/reusable-homey-validate.yml@a6870e7e28cb90bdbfaedd3674039468ebf42f05 # v6.2.0
name: Validate
on:
  pull_request: {}
  push:
    branches: [main]
permissions: {}
